---

#- name: Download Spark
#  shell: http://d3kbcqa49mib13.cloudfront.net/spark-1.0.0.tgz
#  tags: common

#wget http://apache.mirror.nexicom.net/spark/spark-1.0.2/spark-1.0.2-bin-hadoop2.tgz
#tar -xf spark-1.0.0-bin-hadoop1.tgz -C /opt/spark/

- name: create spark root directory
  file: state=directory path={{spark_root}}
  tags: spark

- name: download sources
  get_url: url={{spark_url}} dest={{spark_fulltgz}}
  tags: spark

- name: Extract spark archive
  unarchive: src={{spark_fulltgz}} dest={{spark_root}}
  tags: spark